@echo off
echo 编译usb 重定向及隔离项目......
echo ...
call "..\build.bat"

echo ...
echo 编译结束，复制文件......
echo ....
cd /d %~dp0
set filename=%date:~0,4%%date:~5,2%%date:~8,2%-%time:~0,2%%time:~3,2%-setup.exe
echo "%filename%"

copy "..\udrInstall\安装包制作\Express\SingleImage\DiskImages\DISK1\setup.exe" "%filename%"

echo ...
echo 完成！
pause
